issues:
  fix: true
linters:
  disable-all: true
  enable:
    - gofumpt
    - dupl
    - goconst
    - gocritic
    - goimports
    - gosec
    - misspell
run:
  skip-dirs:
    - .github/
    - /docs
    - /db/migration
    - /db/query
