// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateAccount(ctx context.Context, owner string) (Account, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	GetAccountByOwner(ctx context.Context, owner string) (Account, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	RevokeAccountSessions(ctx context.Context, walletAddress string) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
