// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    wallet_address,
    refresh_token,
    user_agent,
    client_ip,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, wallet_address, refresh_token, user_agent, client_ip, is_revoked, expires_at, created_at
`

type CreateSessionParams struct {
	ID            uuid.UUID `json:"id"`
	WalletAddress string    `json:"wallet_address"`
	RefreshToken  string    `json:"refresh_token"`
	UserAgent     string    `json:"user_agent"`
	ClientIp      string    `json:"client_ip"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.WalletAddress,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, wallet_address, refresh_token, user_agent, client_ip, is_revoked, expires_at, created_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAccountSessions = `-- name: RevokeAccountSessions :execresult
UPDATE sessions
SET is_revoked = true
WHERE wallet_address = $1
`

func (q *Queries) RevokeAccountSessions(ctx context.Context, walletAddress string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, revokeAccountSessions, walletAddress)
}
