// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, owner string) (Account, error)
}

var _ Querier = (*Queries)(nil)
