Project auth_service {
  database_type: 'PostgreSQL'
  Note: '''
    # Auth Service Database
  '''
}

enum role {
    admin
    gamer
}

Table accounts {
  id UUID [default: `gen_random_uuid()`, pk]
  owner varchar [unique, not null]
  role role [not null, default: 'gamer']
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    owner
  }
}

Table sessions {
  id UUID [pk]
  wallet_address varchar [not null, ref: > accounts.owner]
  refresh_token varchar [unique, not null]
  user_agent varchar [not null]
  client_ip varchar [not null]
  is_revoked boolean [not null, default: false]
  expires_at timestamptz [not null]
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    wallet_address
    refresh_token
  }
}
