name: Update Shared Proto Definitions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_shared_proto:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Shared Proto Definitions
        uses: kyamalabs/action-open-pull-request-across-repositories@v0.1.6
        with:
          destination_repository: 'kyamalabs/proto'
          source_folders: 'api/pb,api/proto'
          destination_folders: 'proto/auth/pb,proto/auth/proto'
          destination_head_branch: 'auth-proto-update'
          pr_title: 'feat: update auth service proto'
          commit_message: 'Update auth service proto'
          destination_base_branch: 'main'
          pull_request_reviewers: 'm16w'
        env:
          API_TOKEN_GITHUB: ${{ secrets.PROTO_UPDATE_TOKEN }}
